from pydantic import BaseModel, EmailStr, Field
from typing import Optional, List
from datetime import datetime
import time

class UserCreate(BaseModel):
    username: str = Field(..., min_length=3, max_length=50)
    password: str = Field(..., min_length=6)
    public_key: str = Field(..., description="The Ed25519 Public Key generated by the Android device")

class UserLogin(BaseModel):
    username: str
    password: str

class Device(BaseModel):
    device_id: str
    public_key: str
    device_name: str
    is_active: bool = True

class UserInDB(BaseModel):
    user_id: str
    username: str
    hashed_password: str
    devices: List[Device] = []
    public_key: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    is_online: bool = False
    last_seen: int = Field(default_factory=lambda: int(time.time() * 1000))

class UserResponse(BaseModel):
    user_id: str
    username: str
    public_key: str
    is_online: bool
    
class FCMTokenRequest(BaseModel):
    fcm_token: str